// ============================================================
// pages/laporan.js — Modul Laporan
// Dimuatkan oleh pages/laporan.html
// ============================================================

// ── 19. LAPORAN ──────────────────────────────────────────────
let chartHasil=null,chartStatus=null;
function initLaporan(){kemaskiniLaporanStats();renderLaporanCharts();if(_listenersInit.laporan)return;_listenersInit.laporan=true;document.querySelectorAll('[data-tab-laporan]').forEach(btn=>btn.addEventListener('click',function(){document.querySelectorAll('[data-tab-laporan]').forEach(b=>b.classList.remove('active'));this.classList.add('active');renderLaporanCharts();}));}
function kemaskiniLaporanStats(){const r=JSON.parse(localStorage.getItem('weo_pelanggan')||'[]'),pr=JSON.parse(localStorage.getItem('weo_produk_list')||'[]');const st=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};st('laporanJumlahResit',r.filter(x=>x.jenis==='resit').length);st('laporanJumlahInvois',r.filter(x=>x.jenis==='invoice').length);st('laporanJumlahPelanggan',r.length);st('laporanJumlahProduk',pr.length);}
function renderLaporanCharts(){if(typeof Chart==='undefined')return;const pel=JSON.parse(localStorage.getItem('weo_pelanggan')||'[]'),now=new Date(),bl=[],jd=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);bl.push(d.toLocaleDateString('ms-MY',{month:'short',year:'numeric'}));const j=pel.filter(r=>{try{if(!r.tarikh)return false;const rd=new Date(r.tarikh);return rd.getMonth()===d.getMonth()&&rd.getFullYear()===d.getFullYear();}catch{return false;}}).reduce((s,r)=>s+(parseFloat((r.jumlah||'0').replace(/[^0-9.]/g,''))||0),0);jd.push(j);}const c1=document.getElementById('chartHasil');if(c1){if(chartHasil)chartHasil.destroy();chartHasil=new Chart(c1,{type:'bar',data:{labels:bl,datasets:[{label:'Hasil (RM)',data:jd,backgroundColor:'rgba(99,102,241,0.6)',borderColor:'rgba(99,102,241,1)',borderWidth:1,borderRadius:6}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{color:'#8892a4',callback:v=>'RM '+v.toFixed(0)},grid:{color:'rgba(255,255,255,0.05)'}},x:{ticks:{color:'#8892a4'},grid:{display:false}}}}});}const paid=pel.filter(r=>r.status==='paid').length,unpaid=pel.filter(r=>r.status==='unpaid').length,pending=pel.filter(r=>r.status==='pending').length;const c2=document.getElementById('chartStatus');if(c2){if(chartStatus)chartStatus.destroy();chartStatus=new Chart(c2,{type:'doughnut',data:{labels:['Dibayar','Belum Bayar','Tertangguh'],datasets:[{data:[paid||0,unpaid||0,pending||0],backgroundColor:['rgba(34,197,94,0.8)','rgba(239,68,68,0.8)','rgba(244,164,38,0.8)'],borderColor:['#22c55e','#ef4444','#f4a426'],borderWidth:2}]},options:{responsive:true,plugins:{legend:{position:'bottom',labels:{color:'#8892a4',font:{size:12}}}}}});}}

